version: '3'
services:
  gpsUtil:
    image: gpsutil
    ports:
      - "8082:8082"
    restart: always
  rewardCentral:
    image: rewardcentral
    ports:
      - "8083:8083"
    restart: always
  tripPricer:
    image: trippricer
    ports:
      - "8084:8084"
    restart: always
  tourGuide:
    depends_on:
      - gpsUtil
      - rewardCentral
      - tripPricer
    image: tourguide
    ports:
      - "8080:8080"
    restart: always
